workflows:
  ios-workflow:
    name: iOS Workflow
    # instance_type: mac_mini
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: 'Runner.xcworkspace'
        XCODE_SCHEME: 'Runner'
        BUNDLE_ID: 'YOUR_BUNDLE_ID_HERE'
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log