workflows:
  my-workflow:
    name: My first workflow
    labels:
      - QA
      - PokedexFlutter
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "1.0"
        flutter: stable   # Define the channel name or version (e.g. v1.13.4)
        xcode: latest     # Define latest, edge or version (e.g. 11.2)
        cocoapods: 1.9.1  # Define default or version
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: "Build for iOS"        # Name of the section
      - script: flutter build ios   # The script(s) to be run in that section
    artifacts:
      - build/**/outputs/bundle/**/*.aab